# Generated by Django 6.0.7 on 2026-07-22 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('REQUESTER', '요청자 (공장)'), ('REVIEWER', '1차 검토·관리 창구 (브랜드기획팀)'), ('DESIGNER', '디자인'), ('APPROVER', '최종 검수·반려 판단 (연구소)')], max_length=20)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('is_away', models.BooleanField(default=False, help_text='부재중으로 설정하면 backup_user가 동일 권한으로 처리할 수 있다')),
                ('backup_user', models.ForeignKey(blank=True, help_text='이 사람이 부재중일 때 대신 처리할 담당자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backing_up_for', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '담당자 프로필',
                'verbose_name_plural': '담당자 프로필',
            },
        ),
    ]
