# Generated by Django 6.0.7 on 2026-08-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='카카오톡/문자 알림 수신용 휴대폰번호 (예: 01012345678, - 없이). 비워두면 해당 담당자는 카카오톡/문자를 받지 않음(이메일·인앱 알림은 그대로 감).', max_length=20),
        ),
    ]
