# Generated by Django 6.0.7 on 2026-07-22 05:55

import catalog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='품목명이 바뀌어도 유지되는 고유 식별자', max_length=30, unique=True, verbose_name='품목코드')),
                ('name', models.CharField(max_length=120, verbose_name='품목명')),
                ('category', models.CharField(choices=[('LABEL', '병제품 부착 라벨'), ('PP_BAG', 'PP재질 포대 포장재')], max_length=20)),
                ('product_line', models.CharField(choices=[('FERTILIZER', '비료'), ('CROP_PROTECTION', '작물보호제')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '품목',
                'verbose_name_plural': '품목',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackagingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(editable=False)),
                ('ai_file', models.FileField(upload_to=catalog.models.packaging_upload_to)),
                ('jpg_file', models.ImageField(upload_to=catalog.models.packaging_upload_to)),
                ('status', models.CharField(choices=[('DRAFT', '작업중'), ('FINAL_APPROVED', '최종 승인본'), ('SUPERSEDED', '이전 버전')], default='DRAFT', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_files', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='catalog.product')),
            ],
            options={
                'verbose_name': '포장지 파일',
                'verbose_name_plural': '포장지 파일',
                'ordering': ['product', '-version'],
                'constraints': [models.UniqueConstraint(fields=('product', 'version'), name='unique_product_version')],
            },
        ),
    ]
