# Generated by Django 6.0.7 on 2026-07-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingfile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='꺼두면 데이터는 유지한 채 버전 이력·다운로드 목록에서만 숨겨진다(관리자 화면의 "숨기기").', verbose_name='표시 여부'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='꺼두면 데이터는 유지한 채 품목 목록·검색·신규요청 선택지에서만 숨겨진다(관리자 화면의 "숨기기").', verbose_name='표시 여부'),
        ),
    ]
