# Generated by Django 6.0.7 on 2026-08-26 01:20

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_packagingfile_is_active_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingfile',
            name='jpg_thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=catalog.models.packaging_upload_to),
        ),
        migrations.AlterField(
            model_name='packagingfile',
            name='jpg_file',
            field=models.FileField(upload_to=catalog.models.packaging_upload_to, validators=[catalog.models.validate_visual_file]),
        ),
    ]
