# Generated by Django 6.0.7 on 2026-08-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_packagingfile_jpg_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LABEL', '롤라벨'), ('PP_BAG', '포장재(PP)'), ('PESTICIDE_LABEL', '농약라벨'), ('SOFT_BAG', '소프트백(소량인쇄)'), ('HAND_STICKER', '손스티커'), ('GLOSS_BOX', '유광(박스)')], max_length=20),
        ),
    ]
