# Generated by Django 6.0.7 on 2026-08-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingfile',
            name='is_bulk_upload',
            field=models.BooleanField(default=False, help_text='일괄 업로드(/bulk/)로 등록된 버전인지 — 특정 재발주 건과 연결되지 않아 그 건의 이력(타임라인)에는 안 남으므로, 왜 버전이 바뀌었는지 따로 확인할 수 있도록 "일괄 업로드 이력" 목록에서 구분해 보여준다.'),
        ),
    ]
