# Generated by Django 6.0.7 on 2026-08-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_packagingfile_is_bulk_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingfile',
            name='is_bulk_upload',
            field=models.BooleanField(default=False, help_text='일괄 업로드(/bulk/)로 등록된 버전인지 — 정상 검토 절차 없이 등록된 버전이라, 왜 바뀌었는지 따로 확인할 수 있도록 "일괄 업로드 이력" 목록에서 구분해 보여준다.'),
        ),
    ]
