# Generated by Django 6.0.7 on 2026-07-22 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReorderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(editable=False, help_text='자동 채번되는 요청번호 (예: RQ-20260722-001)', max_length=20, unique=True)),
                ('reason', models.CharField(choices=[('STOCK_SHORTAGE', '재고 소진(임박)'), ('NEEDS_REVISION', '표시사항 등 수정 필요')], max_length=20)),
                ('status', models.CharField(choices=[('SUBMITTED', '요청등록'), ('REVIEW1', '1차검토중'), ('DESIGN_EDIT', '디자인수정중'), ('FINAL_REVIEW', '최종검수중'), ('APPROVED', '승인(전달 대기)'), ('COMPLETED', '완료')], default='REVIEW1', max_length=20)),
                ('used_exception', models.BooleanField(default=False, help_text='3개월 이내 승인 예외로 최종검수를 생략했는지 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='catalog.packagingfile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='catalog.product')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '재발주 건',
                'verbose_name_plural': '재발주 건',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workflow.reorderrequest')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMITTED', '요청 등록'), ('REVIEW_TO_FINAL', '최종본 확인 → 최종검수 요청'), ('REVIEW_REQUEST_EDIT', '수정 요청'), ('DESIGN_UPLOADED', '디자인파일 수정 업로드'), ('FINAL_APPROVE', '최종 승인'), ('FINAL_REVISION', '수정 필요(경미)'), ('FINAL_REJECT', '반려'), ('HANDOFF', '최종파일 전달 · 완료'), ('EXCEPTION_SKIP', '3개월 예외 적용(최종검수 생략)'), ('NOTIFY', '알림 발송')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('channel', models.CharField(choices=[('SYSTEM', '시스템'), ('EMAIL_MOCK', '이메일(모의)'), ('KAKAO_MOCK', '카카오톡/문자(모의)')], default='SYSTEM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workflow.reorderrequest')),
            ],
            options={
                'verbose_name': '이력',
                'verbose_name_plural': '이력',
                'ordering': ['created_at'],
            },
        ),
    ]
