# Generated by Django 6.0.7 on 2026-07-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestevent',
            name='channel',
            field=models.CharField(choices=[('SYSTEM', '시스템'), ('EMAIL_MOCK', '이메일'), ('KAKAO_MOCK', '카카오톡/문자(모의)')], default='SYSTEM', max_length=20),
        ),
    ]
