# Generated by Django 6.0.7 on 2026-08-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_alter_reorderrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reorderrequest',
            name='detail',
            field=models.TextField(blank=True, help_text='요청자가 남긴 구체적인 요청사항(선택)'),
        ),
    ]
