# Generated by Django 6.0.7 on 2026-08-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestevent',
            name='attachment',
            field=models.FileField(blank=True, help_text='표시사항 가이드 등 지시사항에 첨부하는 참고 파일(선택) — 예: 1차검토에서 디자인 수정 요청 시', null=True, upload_to='request_attachments/%Y/%m/'),
        ),
    ]
