# Generated by Django 6.0.7 on 2026-08-24 04:17

import workflow.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_requestevent_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestevent',
            name='attachment_original_name',
            field=models.CharField(blank=True, help_text='원본 파일명(저장 키는 한글 등을 피해 랜덤값으로 바뀌므로, 화면 표시용으로 따로 보관)', max_length=255),
        ),
        migrations.AlterField(
            model_name='requestevent',
            name='attachment',
            field=models.FileField(blank=True, help_text='표시사항 가이드 등 지시사항에 첨부하는 참고 파일(선택) — 예: 1차검토에서 디자인 수정 요청 시', null=True, upload_to=workflow.models.request_attachment_upload_to),
        ),
    ]
