# Generated by Django 6.0.7 on 2026-08-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_requestevent_attachment_original_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestevent',
            name='email_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='requestevent',
            name='kakao_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='requestevent',
            name='push_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
