# Generated by Django 6.0.7 on 2026-08-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_requestevent_email_status_requestevent_kakao_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reorderrequest',
            name='reason',
            field=models.CharField(choices=[('STOCK_SHORTAGE', '재고 소진(임박)'), ('NEEDS_REVISION', '표시사항 등 수정 필요'), ('BULK_UPLOAD', '일괄 업로드')], max_length=20),
        ),
        migrations.AlterField(
            model_name='requestevent',
            name='action',
            field=models.CharField(choices=[('SUBMITTED', '요청 등록'), ('REVIEW_TO_FINAL', '최종본 확인 → 최종검수 요청'), ('REVIEW_REQUEST_EDIT', '수정 요청'), ('DESIGN_UPLOADED', '디자인파일 수정 업로드'), ('FINAL_APPROVE', '최종 승인'), ('FINAL_REVISION', '수정 필요(경미)'), ('FINAL_REJECT', '반려'), ('HANDOFF', '최종파일 전달 · 완료'), ('EXCEPTION_SKIP', '3개월 예외 적용(최종검수 생략)'), ('BULK_UPLOAD', '일괄 업로드로 파일 강제 갱신'), ('NOTIFY', '알림 발송'), ('CANCELLED', '요청 취소'), ('DESIGN_REJECT', '디자인 반려(1차검토로)'), ('APPROVAL_REVERTED', '승인 취소(최종검수로 되돌림)')], max_length=30),
        ),
    ]
