# Generated by Django 6.0.7 on 2026-08-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_alter_reorderrequest_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reorderrequest',
            options={'ordering': ['-created_at'], 'verbose_name': '발주 건', 'verbose_name_plural': '발주 건'},
        ),
        migrations.AlterField(
            model_name='reorderrequest',
            name='reason',
            field=models.CharField(choices=[('STOCK_SHORTAGE', '재고 소진(임박)'), ('NEEDS_REVISION', '표시사항 등 수정 필요'), ('BULK_UPLOAD', '파일관리요청')], max_length=20),
        ),
    ]
