# Generated by Django 6.0.7 on 2026-08-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_alter_reorderrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reorderrequest',
            name='reason',
            field=models.CharField(choices=[('NEEDS_REVISION', '디자인 수정 요청'), ('BULK_UPLOAD', '파일 확인 요청'), ('STOCK_SHORTAGE', '그 외 기타')], max_length=20),
        ),
    ]
